admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation

front_end:
    resource: "@FrontEndBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
